---
title: "cards_semanais"
author: "Plinio"
date: "23/02/2023"
output: html_document
---

```{r}
# ============================================================================
# VARIÁVEL DE CONTROLE: SEMANA EPIDEMIOLÓGICA ATUAL
# ATUALIZAR este valor a cada semana para refletir a SE corrente
# ============================================================================
corteSemana = 19 ### ATUALIZAR !!!
```

```{r}
# ============================================================================
# URL DOS DADOS INTERNACIONAIS (Johns Hopkins University - CSSE)
# Dados diários dos EUA do repositório COVID-19 da JHU
# ATUALIZAR a data no nome do arquivo no formato MM-DD-AAAA
# ============================================================================
url_juh_us = "https://raw.githubusercontent.com/CSSEGISandData/COVID-19/master/csse_covid_19_data/csse_covid_19_daily_reports_us/5-04-2024.csv" ### ATUALIZAR MM/DD/AAAA!!!
# https://github.com/CSSEGISandData/COVID-19/tree/master/csse_covid_19_data
```

#### CARREGAR PACOTES

```{r warning = F, message = F}
# ============================================================================
# BIBLIOTECAS NECESSÁRIAS
# ----------------------------------------------------------------------------
# tidyverse    : Manipulação e visualização de dados
# lubridate    : Manipulação de datas e semanas epidemiológicas
# data.table   : Leitura rápida de CSV (fread) e manipulação eficiente
# openxlsx     : Leitura/escrita de Excel
# hablar       : Funções sum_(), min_() que tratam NA como 0
# extrafont    : Acesso a fontes tipográficas adicionais para gráficos
# hrbrthemes   : Temas elegantes para ggplot2 (theme_ipsum)
# gghighlight  : Destaque condicional de elementos em gráficos
# udunits2     : Conversão de unidades (usado por pacotes geoespaciais)
# sf           : Manipulação de dados geoespaciais (Simple Features)
# brazilmaps   : Mapas do Brasil (estados, municípios, regiões)
# geobr        : Dados geográficos do Brasil (IBGE)
# ggspatial    : Elementos cartográficos para ggplot2
# ggsn         : Escala e norte para mapas em ggplot2
# ggflags      : Bandeiras como elementos gráficos
# ggrepel      : Rótulos sem sobreposição em gráficos
# ============================================================================
library(tidyverse)
library(lubridate)
library(data.table)
library(openxlsx)
library(hablar)
library(extrafont)
library(hrbrthemes)
library(gghighlight)
library(udunits2)
library(sf)
library(brazilmaps)
library(geobr)
library(ggspatial)
library(ggsn)
library(ggflags)
library(ggrepel)
```

### PARTE 1 - BRASIL

#### IMPORTAR DADOS (BRASIL)

```{r}
# ============================================================================
# IMPORTAÇÃO DO DATASET CONSOLIDADO DE CONTROLE
# Lê o arquivo CSV gerado pelo Notebook 3 (RNotebook3_Paineis_SVS_NOVO.Rmd)
# contendo dados hierárquicos de todos os níveis (Brasil, UF, Município)
# NOTA: Atualizar o caminho e a data do arquivo (AAAAMMDD) conforme necessário
# encoding UTF-8 para preservar caracteres acentuados
# ============================================================================
#DT_CONTROL = fread(file = "C:/Users/pbrte/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/1_Data/Dados_Controle/DT_Monitora_COVID_20240105.csv", encoding = "UTF-8") ## ATUALIZAR !!!

DT_CONTROL = fread(file = "C:/Users/audencio.victor/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/1_Data/Dados_Controle/DT_Monitora_COVID_20240511.csv", encoding = "UTF-8") ## ATUALIZAR !!!
```

```{r}
# ============================================================================
# IMPORTAÇÃO DA BASE DE MUNICÍPIOS (COM COORDENADAS GEOGRÁFICAS)
# Contém latitude (LAT) e longitude (LONG) de cada município para
# posicionamento nos mapas
# ============================================================================
#DT_MUN = read.xlsx("C:/Users/pbrte/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/1_Data/DADOSMUNBR_novo.xlsx", sheet = 1)

DT_MUN = read.xlsx("C:/Users/audencio.victor/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/1_Data/DADOSMUNBR_novo.xlsx", sheet = 1)
```

```{r}
# ============================================================================
# IMPORTAÇÃO DAS ESTIMATIVAS POPULACIONAIS TCU 2019
# Dados populacionais usados para cálculo de taxas (incidência, mortalidade)
# - codigoUF + codigoMUN: concatenados para formar CODIGOMUN7
# - CODIGOMUN7 truncado para 6 dígitos (sem dígito verificador)
# - Se código do município for NA, usa o código da UF
# ============================================================================
#dadostcu2019 <- readxl::read_excel("C:/Users/pbrte/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/1_Data/estimativa_TCU_2019_20200427.xls", sheet = 4)

dadostcu2019 <- readxl::read_excel("C:/Users/audencio.victor/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/1_Data/estimativa_TCU_2019_20200427.xls", sheet = 4)



dadostcu2019 <- dadostcu2019 %>%
  #mutate(codigoMUN = str_replace_na("")) %>%
  mutate(CODIGOMUN7 = str_c(codigoUF, codigoMUN)) %>%
  mutate(CODIGOMUN7 = parse_number(str_sub(CODIGOMUN7, end = 6))) %>%
  mutate(CODIGOMUN7 = case_when(is.na(CODIGOMUN7) ~ codigoUF, TRUE ~ CODIGOMUN7)) %>%
  select(CODIGOMUN7, POP_TCU2019)

# DT_CONTROL = DT_CONTROL %>% left_join(dadostcu2020, by = c("CODIGOLOCAL" = "CODIGOMUN7"))
```

#### PREPARAR DADOS

```{r}
# Filtro opcional por data máxima (desativado)
#DT_CONTROL = DT_CONTROL %>%
#  filter(data <= "2022-10-15") ## ATUALIZAR !!!
```

```{r}
# ============================================================================
# ADICIONAR ANO EPIDEMIOLÓGICO
# epiyear(): calcula o ano epidemiológico (pode diferir do calendário
# na primeira/última semana do ano)
# ============================================================================
DT_CONTROL = DT_CONTROL %>%
  mutate(anoEpi = epiyear(data)) #%>%
  #filter(!(anoEpi == 2023 & semanaEpi > corteSemana)) ## ATUALIZAR !!!
```

```{r}
# ============================================================================
# PREPARAR COORDENADAS DOS MUNICÍPIOS
# Extrai LAT e LONG da base de municípios, truncando o código para 6 dígitos
# ============================================================================
DT_MUN = DT_MUN %>% select(CODIGOMUN, LAT, LONG) %>% mutate(CODIGOMUN = parse_number(str_sub(CODIGOMUN, end = 6)))
```

```{r}
# Converter strings vazias para NA usando sjmisc
DT_CONTROL = sjmisc::set_na(DT_CONTROL, na = "")
```

```{r}
# Converter data para formato Date e vincular coordenadas geográficas
DT_CONTROL = DT_CONTROL %>% mutate(data = ymd(data)) %>% left_join(DT_MUN, by = c("CODIGOLOCAL" = "CODIGOMUN"))
```

```{r}
# ============================================================================
# VINCULAR POPULAÇÃO TCU 2019
# Faz junção com dados populacionais; renomeia para resolver conflito
# de nomes (POP_TCU2019.x = coluna do DT_CONTROL original)
# ============================================================================
DT_CONTROL = DT_CONTROL %>% full_join(dadostcu2019, by = c("CODIGOLOCAL" = "CODIGOMUN7"))

DT_CONTROL = DT_CONTROL %>%
  rename(POP_TCU2019 = POP_TCU2019.x)
```

```{r}
# ============================================================================
# CALCULAR DATA MÍNIMA POR SEMANA EPIDEMIOLÓGICA
# minData: primeiro dia de cada semana epidemiológica,
# usado para agrupar dados semanais e como eixo X dos gráficos
# ============================================================================
DT_CONTROL = DT_CONTROL %>%
  group_by(anoEpi, semanaEpi) %>%
  mutate(minData = min_(data)) %>%
  ungroup()
```

#### CHECAR DADOS

```{r}
# ============================================================================
# VERIFICAÇÃO DOS TOTAIS NACIONAIS
# Exibe os dados do último dia para o Brasil (ABRANGENCIA == 1)
# ============================================================================
DT_CONTROL %>% filter(ABRANGENCIA == 1, data == max(data)) %>% select(NOMELOCAL, data, semanaEpi, casosAcumulado, obitosAcumulado, casosNovos, obitosNovos)
```

```{r}
# ============================================================================
# VERIFICAÇÃO DA COBERTURA MUNICIPAL
# Conta municípios totais, com casos e com óbitos no último dia disponível
# Exclui registros genéricos ($0000 = municípios sem código IBGE)
# ============================================================================
cbind(DT_CONTROL %>% filter(ABRANGENCIA == 7, data == max(data), CODIGOMUN7 != "$0000") %>% summarise(municipioTotal = n_distinct(CODIGOMUN7)),

DT_CONTROL %>% filter(ABRANGENCIA == 7, casosAcumulado > 0) %>% filter(data == max(data), CODIGOMUN7 != "$0000") %>% summarise(municipioCasos = n_distinct(CODIGOMUN7)),

DT_CONTROL %>% filter(ABRANGENCIA == 7, obitosAcumulado > 0) %>% filter(data == max(data), CODIGOMUN7 != "$0000") %>% summarise(municipioObitos = n_distinct(CODIGOMUN7)))
```

##Mapas

```{r}
# ============================================================================
# MAPA DE TENDÊNCIA POR UF: COMPARAÇÃO ENTRE DUAS SEMANAS CONSECUTIVAS
# Calcula a variação percentual de casos e óbitos novos entre a penúltima
# e a última semana epidemiológica para cada UF:
# - changeCasosNovos: variação % de casos novos
# - changeObitosNovos: variação % de óbitos novos
# Classifica cada UF em uma das 3 categorias (limiar de ±5%):
# - Redução: variação < -5%
# - Estabilização: variação entre -5% e +5%
# - Incremento: variação > +5%
# Vincula com geometria dos estados para geração de mapas
# ============================================================================
tbMapUF = DT_CONTROL %>%
  filter(ABRANGENCIA == 3, minData == max(minData) - 7) %>%
  select(CODIGOLOCAL, casosNovos, obitosNovos) %>%
  group_by(CODIGOLOCAL) %>%
  summarise(casosNovosAntes = sum_(casosNovos), obitosNovosAntes = sum_(obitosNovos)) %>%
  #mutate(casosNovosAntes = case_when(casosNovosAntes <0 ~ 54, TRUE ~ as.numeric(as.character(casosNovosAntes))))%>%
  left_join(
    DT_CONTROL %>%
      filter(ABRANGENCIA == 3, minData == max(minData)) %>%
      select(CODIGOLOCAL, casosNovos, obitosNovos) %>%
      group_by(CODIGOLOCAL) %>%
      summarise(casosNovosDepois = sum_(casosNovos), obitosNovosDepois = sum_(obitosNovos)),
      by = c("CODIGOLOCAL" = "CODIGOLOCAL")) %>%
      mutate(changeCasosNovos =
               round(((casosNovosDepois - casosNovosAntes) / casosNovosAntes) * 100, 0),
             changeObitosNovos =
               round(((obitosNovosDepois - obitosNovosAntes) / obitosNovosAntes) * 100,
                     0)) %>%
  mutate(catsCasosNovos = case_when(changeCasosNovos < -5 ~ "Redução",
                               between(changeCasosNovos, -5, 5) ~ "Estabilização",
                               changeCasosNovos > 5 ~ "Incremento",
                               TRUE ~ NA_character_)) %>%
  mutate(catsObitosNovos = case_when(changeObitosNovos < -5 ~ "Redução",
                               between(changeObitosNovos, -5, 5) ~ "Estabilização",
                               changeObitosNovos > 5 ~ "Incremento",
                               TRUE ~ NA_character_))



tbMapUF = get_brmap("State") %>% inner_join(tbMapUF, c("State" = "CODIGOLOCAL"))
```

```{r}
# ============================================================================
# TRATAMENTO DE VALORES INFINITOS
# Quando a semana anterior tinha 0 casos/óbitos e a atual tem > 0,
# a variação percentual resulta em Inf. Substitui por 100% (aumento total)
# ============================================================================
tbMapUF<-tbMapUF %>%
  mutate(changeObitosNovos= case_when(changeObitosNovos== Inf ~ 100,
                                      TRUE ~ changeObitosNovos))

tbMapUF<-tbMapUF %>%
  mutate(changeCasosNovos= case_when(changeCasosNovos== Inf ~ 100,
                                      TRUE ~ changeCasosNovos))
```

```{r}
# ============================================================================
# AJUSTES MANUAIS (DESATIVADOS)
# Blocos comentados para correção manual de valores específicos
# quando há inconsistências nos dados de estados individuais.
# Manter comentado exceto quando necessário ajuste pontual
# ============================================================================
#tbMapUF$changeCasosNovos[1] <- 100
#tbMapUF$changeCasosNovos[2] <- 100
#tbMapUF$changeCasosNovos[6] <- 100
#tbMapUF$changeCasosNovos[9] <- 100
#tbMapUF$changeCasosNovos[17] <- 100
#tbMapUF$changeCasosNovos[18] <- 100

#tbMapUF$changeCasosNovos[2] <- 0
#tbMapUF$changeCasosNovos[17] <- 0

#tbMapUF$catsCasosNovos[2] <- "Estabilização"
#tbMapUF$catsCasosNovos[17] <- "Estabilização"
#tbMapUF$catsCasosNovos[24] <- "Estabilização"

#tbMapUF$changeObitosNovos[6] <- -100

#tbMapUF$changeObitosNovos[1] <- 0
#tbMapUF$changeObitosNovos[2] <- 0
#tbMapUF$changeObitosNovos[3] <- 0
#tbMapUF$changeObitosNovos[4] <- 0
#tbMapUF$changeObitosNovos[5] <- 0
#tbMapUF$changeObitosNovos[6] <- 0
#tbMapUF$changeObitosNovos[7] <- 0
#tbMapUF$changeObitosNovos[8] <- 0
#tbMapUF$changeObitosNovos[9] <- 0
#tbMapUF$changeObitosNovos[10] <- 0
#tbMapUF$changeObitosNovos[12] <- 0
#tbMapUF$changeObitosNovos[14] <- 0
#tbMapUF$changeObitosNovos[15] <- 0
#tbMapUF$changeObitosNovos[16] <- 0
#tbMapUF$changeObitosNovos[17] <- 0
#tbMapUF$changeObitosNovos[18] <- 0
#tbMapUF$changeObitosNovos[19] <- 0
#tbMapUF$changeObitosNovos[26] <- 0

#tbMapUF$catsObitosNovos[1] <- "Estabilização"
#tbMapUF$catsObitosNovos[2] <- "Estabilização"
#tbMapUF$catsObitosNovos[3] <- "Estabilização"
#tbMapUF$catsObitosNovos[4] <- "Estabilização"
#tbMapUF$catsObitosNovos[6] <- "Estabilização"
#tbMapUF$catsObitosNovos[7] <- "Estabilização"
#tbMapUF$catsObitosNovos[8] <- "Estabilização"
#tbMapUF$catsObitosNovos[9] <- "Estabilização"
#tbMapUF$catsObitosNovos[10] <- "Estabilização"
#tbMapUF$catsObitosNovos[12] <- "Estabilização"
#tbMapUF$catsObitosNovos[14] <- "Estabilização"
#tbMapUF$catsObitosNovos[15] <- "Estabilização"
#tbMapUF$catsObitosNovos[16] <- "Estabilização"
#tbMapUF$catsObitosNovos[17] <- "Estabilização"
#tbMapUF$catsObitosNovos[18] <- "Estabilização"
#tbMapUF$catsObitosNovos[26] <- "Estabilização"

#tbMapUF$obitosNovosDepois[6] <- 0
```

```{r}
# ============================================================================
# MAPA DE TENDÊNCIA: CASOS NOVOS POR UF
# Mapa coroplético mostrando a variação % de casos novos entre duas semanas:
# - Verde (#99d8c9): Redução (< -5%)
# - Cinza (#f0f0f0): Estabilização (entre -5% e +5%)
# - Vermelho (#fc9272): Incremento (> +5%)
# Rótulos mostram a variação percentual de cada estado.
# Estados do Nordeste (RN-AL-SE, códigos 24-28) usam geom_label_repel
# para evitar sobreposição de rótulos. DF (53) usa nudge vertical.
# Inclui barra de escala de 500km no canto inferior direito.
# ============================================================================
gg15A = ggplot(tbMapUF) +
  geom_sf(aes(fill = catsCasosNovos), size = 0.5) +
  geom_sf(data = get_brmap("Region"), fill = "transparent", colour = "black", size = .8) +
  scale_fill_manual(name = "Casos novos",
                    breaks = c("Redução","Estabilização","Incremento"),
                    values = c("#99d8c9","#f0f0f0","#fc9272"),
                    labels = c(paste0("Redução ", "(", n_distinct(tbMapUF$State[tbMapUF$catsCasosNovos == "Redução"]), ")"),
                               paste0("Estabilização ", "(", n_distinct(tbMapUF$State[tbMapUF$catsCasosNovos == "Estabilização"]), ")"),
                               paste0("Incremento ", "(", n_distinct(tbMapUF$State[tbMapUF$catsCasosNovos == "Incremento"]), ")"))) +
  geom_sf_label(data = filter(tbMapUF, !State %in% c(24:28, 53)),
                aes(label = paste0(changeCasosNovos, "%")), size = 5) +
  geom_label_repel(data = filter(tbMapUF, State %in% c(24:28)),
                   aes(label = paste0(changeCasosNovos, "%"), geometry = geometry),
                   size = 5, stat = "sf_coordinates", force = 1, nudge_x = 0.2,
                   direction = "x") +
  geom_label_repel(data = filter(tbMapUF, State %in% c(53)),
                   aes(label = paste0(changeCasosNovos, "%"), geometry = geometry),
                   size = 5, stat = "sf_coordinates", force = 1, nudge_y = 0.2,
                   direction = "y") +
  labs(title = "") +
  theme_void(base_size = 14) +
  theme(legend.position = c(0.2, 0.25), axis.text = element_blank(),
        legend.title = element_text(face = "bold"),
        plot.tag = element_text(face = "bold")) +
  scalebar(tbMapUF, dist = 500, location = "bottomright", transform = T,
           dist_unit = "km", st.dist = 0.03, st.size = 3, model = "WGS84") #+
 # north(tbMapUF, symbol = 2, scale = .1)
```

```{r}
# ============================================================================
# MAPA DE TENDÊNCIA: ÓBITOS NOVOS POR UF
# Mesma estrutura do mapa de casos, mas para óbitos novos.
# Cores e categorias idênticas (Redução/Estabilização/Incremento)
# ============================================================================
gg15B = ggplot(tbMapUF) +
  geom_sf(aes(fill = catsObitosNovos), size = 0.5) +
  geom_sf(data = get_brmap("Region"), fill = "transparent", colour = "black", size = .8) +
  scale_fill_manual(name = "Óbitos novos",
                    breaks = c("Redução","Estabilização","Incremento"),
                    values = c("#99d8c9","#f0f0f0","#fc9272"),
                    labels = c(paste0("Redução ", "(", n_distinct(tbMapUF$State[tbMapUF$catsObitosNovos == "Redução"]), ")"),
                               paste0("Estabilização ", "(", n_distinct(tbMapUF$State[tbMapUF$catsObitosNovos == "Estabilização"]), ")"),
                               paste0("Incremento ", "(", n_distinct(tbMapUF$State[tbMapUF$catsObitosNovos == "Incremento"]), ")"))) +
  geom_sf_label(data = filter(tbMapUF, !State %in% c(24:28, 53)),
                aes(label = paste0(changeObitosNovos, "%")), size = 5) +
  ggrepel::geom_label_repel(data = filter(tbMapUF, State %in% c(24:28)),
                            aes(label = paste0(changeObitosNovos, "%"), geometry = geometry),
                            size = 5, stat = "sf_coordinates", force = 1, nudge_x = 0.2,
                            direction = "x") +
  geom_label_repel(data = filter(tbMapUF, State %in% c(53)),
                   aes(label = paste0(changeObitosNovos, "%"), geometry = geometry),
                   size = 5, stat = "sf_coordinates", force = 1, nudge_y = 0.2,
                   direction = "y") +
  labs(title = "") +
  theme_void(base_size = 14) +
  theme(legend.position = c(0.2, 0.25),
        axis.text = element_blank(),
        legend.title = element_text(face = "bold"),
        plot.tag = element_text(face = "bold")) +
  scalebar(tbMapUF, dist = 500, location = "bottomright", transform = T,
           dist_unit = "km", st.dist = 0.03, st.size = 3, model = "WGS84")# +
 # north(tbMapUF, symbol = 2, scale = .1)
```

###salva mapas

```{r}
# ============================================================================
# SALVAR MAPAS DE TENDÊNCIA E TABELAS DE DADOS
# - Salva mapas como PNG em alta resolução (retina = 320 DPI)
# - Converte códigos numéricos dos estados para siglas
# - Exporta tabelas com dados de comparação semanal para Excel
# NOTA: Atualizar a pasta da SE (ex: "SE 19 2024") a cada semana
# ============================================================================
#setwd("C:/Users/pbrte/OneDrive - Ministério da Saúde/Área de Trabalho/cards/")
#setwd("C:/Users/wanderley.junior/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/mapas/SE 13 2024/") ##ATUALIZAR

#setwd("C:/Users/eucil/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/mapas/SE 13 2023/") ##ATUALIZAR

#setwd("C:/Users/pbrte/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/mapas/SE 47 2023/") ##ATUALIZAR

ggsave(gg15A, width = 200, height = 170, units = "mm", file = "Fig_17A.png", dpi = "retina")
ggsave(gg15B, width = 200, height = 170, units = "mm", file = "Fig_17B.png", dpi = "retina")

# Remove geometria para converter em tabela simples e mapeia códigos para siglas
tbMapUF$geometry <- NULL

tbMapUF <-  tbMapUF %>%
  mutate(State = case_when(State == 11 ~ "RO", State == 12 ~ "AC", State == 13 ~ "AM", State == 14 ~ "RR", State == 15 ~ "PA", State == 16 ~ "AP", State == 17 ~ "TO", State == 21 ~ "MA", State == 22 ~ "PI", State == 23 ~ "CE", State == 24 ~ "RN", State == 25 ~ "PB", State == 26 ~ "PE", State == 27 ~ "AL", State == 28 ~ "SE", State == 29 ~ "BA", State == 31 ~ "MG", State == 32 ~ "ES", State == 33 ~ "RJ", State == 35 ~ "SP", State == 41 ~ "PR", State == 42 ~ "SC", State == 43 ~ "RS", State == 50 ~ "MS", State == 51 ~ "MT", State == 52 ~ "GO", State == 53 ~ "DF"))

tbMapUF_Casos <- tbMapUF %>%
  select(State, casosNovosAntes, casosNovosDepois, changeCasosNovos)

tbMapUF_Obitos <- tbMapUF %>%
  select(State, obitosNovosAntes, obitosNovosDepois, changeObitosNovos)


write.xlsx(tbMapUF_Casos, file = "C:/Users/audencio.victor/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/mapas/SE 19 2024/tbMapUF_Casos.xlsx", overwrite = T) ###ATUALIZAR

#write.xlsx(tbMapUF_Obitos, file = "C:/Users/wanderley.junior/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/mapas/SE 13 2024/tbMapUF_Obitos.xlsx", overwrite = T) ###ATUALIZAR

write.xlsx(tbMapUF_Obitos, file = "C:/Users/audencio.victor/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/mapas/SE 19 2024/tbMapUF_Obitos.xlsx", overwrite = T) ###ATUALIZAR

#write.xlsx(tbMapUF_Casos, file = "C:/Users/pbrte/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/mapas/SE 47 2023/tbMapUF_Casos.xlsx", overwrite = T) ###ATUALIZAR

#write.xlsx(tbMapUF_Obitos, file = "C:/Users/pbrte/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/mapas/SE 47 2023/tbMapUF_Obitos.xlsx", overwrite = T) ###ATUALIZAR
#write.xlsx(tbMapUF, file = "tbMapUF.xlsx", overwrite = T)

```

####teste - barras

```{r}
# ============================================================================
# PREPARAÇÃO DOS DADOS PARA GRÁFICOS DE BARRAS SEMANAIS
# Filtra dados nacionais (ABRANGENCIA == 1) e adiciona semana epidemiológica
# e ano. Linhas comentadas: ajustes manuais para corrigir inconsistências
# em datas específicas (ex: dados negativos de AP em SE 35/2023)
# ============================================================================
tbdia <- DT_CONTROL %>%
  filter(ABRANGENCIA == 1) %>%
  select(data, casosNovos, obitosNovos) %>%
  mutate(SE = epiweek(data)) %>%
  mutate(anoepi = year(data))

#tbdia$obitosNovos[1286] <- 65 ###AJUSTE DE BANCO DE DADOS NOS ÓBITOS DE AP (-205) E PR (-1) EM 02/09/2023 SE 35
#tbdia$obitosNovos[1293] <- 117 ###AJUSTE BANCO DE DADOS NOS ÓBITOS DE AP (0) E MS (-1) EM 09/09/2023 SE 36
#tbdia$obitosNovos[1300] <- 356 ###AJUSTE BANCO DE DADOS NOS ÓBITOS DE AP (+205) EM 19/09/2023 SE 37
```

```{r}
# ============================================================================
# FILTRO PARA TRANSIÇÃO ENTRE ANOS (DESATIVADO)
# Usar apenas quando a semana epidemiológica cruza a virada do ano
# ============================================================================
######UTILIZAR ESSAS LINHAS SOMENTE NA TRANSIÇÃO DOS ANOS!!!
#
#tbdia2023 <- tbdia %>%
#  #filter(SE >= 10 & anoepi == 2023)
#
#tbdia2024 <- tbdia %>%
#  filter(anoepi == 2024)
#
#tbdia <- rbind(tbdia2023)#,tbdia2024)
```

```{r}
# ============================================================================
# AGREGAÇÃO SEMANAL
# Soma casos e óbitos por semana epidemiológica e calcula a média diária
# (total semanal / 7 dias) para suavização da série
# ============================================================================
tbdia <- tbdia %>%
  group_by(SE,anoepi) %>%
  summarize(casosNovos = sum(casosNovos), obitosNovos = sum(obitosNovos)) %>%
  mutate(smaCasosNovos = casosNovos/7,)%>%
  mutate(smaObitosNovos = obitosNovos/7)
```

```{r}
# Arredondar médias para 1 casa decimal
tbdia$smaCasosNovos <- round(tbdia$smaCasosNovos, 1)
tbdia$smaObitosNovos <- round(tbdia$smaObitosNovos, 1)
```

##arquivo de data para padronizar o gráfico e ter label no mesmo

```{r}
# ============================================================================
# VINCULAR DATAS DE REFERÊNCIA DAS SEMANAS EPIDEMIOLÓGICAS
# Arquivo Data_SE_base.xlsx contém o mapeamento entre SE/ano e a data
# de início de cada semana, usado como eixo X nos gráficos de barras
# NOTA: Atualizar o caminho conforme o usuário
# ============================================================================
#Data_SE_base<-openxlsx::read.xlsx("C:/Users/pbrte/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/Data_SE_base.xlsx", detectDates = T)


#Data_SE_base<-openxlsx::read.xlsx("C:/Users/wanderley.junior/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/Data_SE_base.xlsx", detectDates = T)


Data_SE_base<-openxlsx::read.xlsx("C:/Users/audencio.victor/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/Data_SE_base.xlsx", detectDates = T)


tbdia<-tbdia %>%
  left_join(Data_SE_base, by= c("anoepi","SE"))
```

###aqui vai ter que filtrar manter só cinco semanas pq os gráficos estão configurados para sete barras ####ATUALIZAR

```{r}
# ============================================================================
# FILTRAR ÚLTIMAS 5 SEMANAS PARA EXIBIÇÃO NO GRÁFICO
# ATUALIZAR: o ano e os números das SEs a cada semana
# Os gráficos são configurados para mostrar 5 barras (5 semanas)
# ============================================================================
tbdia <- tbdia %>%
  filter(anoepi == 2024) %>%
  filter(SE == 15|SE == 16 |SE == 17|SE == 18|SE == 19) ###ATUALIZAR QUANDO VIRAR O ANO E ATUALIZAR AS SEMANAS
  #filter(anoepi == 2024) ###ATUALIZAR QUANDO VIRAR O ANO

tbdia$minData_n <- as.Date(tbdia$minData_n)
```

##gráfico casos por SE

```{r}
# ============================================================================
# GRÁFICO DE BARRAS: CASOS NOVOS POR SEMANA EPIDEMIOLÓGICA
# - Barras em azul escuro (#010b59) com borda azul (#0016bf)
# - Eixo Y: 0 a 75.000 casos (escala com separador de milhar)
# - Rótulos numéricos acima de cada barra (tamanho 14, negrito)
# - Eixo X: número da SE (labels = tbdia$SE)
# - Tema hrbrthemes (theme_ipsum) sem grade, texto grande (30pt)
# - Formatação brasileira: ponto como separador de milhar, vírgula decimal
# ============================================================================
Plot_casos_mes<-ggplot(data = tbdia) +
  geom_bar(aes(x=minData_n, y=casosNovos), width=6, stat="identity", alpha = 0.5, colour="#0016bf", fill="#010b59")+
  #geom_line(aes(x=minData_n, y = smaCasosNovos, colour = "#141313"), size = 1.5) +
  scale_x_date(labels = tbdia$SE, breaks = tbdia$minData_n, expand = c(0, 0),guide = guide_axis(check.overlap = TRUE)) +
  scale_y_continuous(limits = c(0, 75000), breaks = seq(0, 75000, 5000), expand = c(0,0),
                      labels = scales::label_comma(big.mark = ".", decimal.mark = ","))+
  #scale_colour_manual(name = "", labels = c("#141313" = "Média por SE"), values = c("#141313" = "#141313")) +
  geom_text(aes(x=minData_n, y=casosNovos, label = format(casosNovos, big.mark = ".", decimal.mark = ",")), colour = "black", hjust = 0.5,
  vjust = -1, fontface = "bold", size=14) +
  #geom_label(aes(x=minData_n, y=smaCasosNovos, label = format(smaCasosNovos, big.mark = ".", decimal.mark = ",")), colour = "black", hjust = 0.5, vjust = 0.4, fontface = "bold", size=14) +
  labs(title = "Casos da covid-19 por SE da notificação",
    x = "Semana epidemiológica", y = "Número de casos novos de covid") +
  theme_ipsum(grid = F, base_size = 16, axis_text_size = 30) +
  theme(legend.position = "bottom",
        axis.line.x = element_line(colour = "black"),
        axis.ticks.x = element_line(colour = "black"),
        axis.title.x = element_text(size = 30),
        axis.text.x = element_text(size = 30),
        axis.title.y = element_text(size = 30),
        plot.title = element_text(size = 30),
        legend.text = element_text(size = 30))
```

##gráfico óbitos por SE

```{r}
# ============================================================================
# GRÁFICO DE BARRAS: ÓBITOS NOVOS POR SEMANA EPIDEMIOLÓGICA
# - Barras em vermelho escuro (#7d0606) com borda vermelha (#d60909)
# - Eixo Y: 0 a 400 óbitos
# - Mesma estrutura visual do gráfico de casos
# ============================================================================
Plot_obitos_mes<-ggplot(data = tbdia) +
  geom_bar(aes(x=minData_n, y=obitosNovos), width=6, stat="identity", alpha = 0.5, colour="#d60909", fill="#7d0606")+
  #geom_line(aes(x=minData_n, y = smaObitosNovos, colour = "#141313"), size = 1.5) +
  scale_x_date(labels = tbdia$SE, breaks = tbdia$minData_n, expand = c(0, 0),guide = guide_axis(check.overlap = TRUE)) +
  scale_y_continuous(limits = c(0, 400), breaks = seq(0, 400, 50), expand = c(0,0),
                      labels = scales::label_comma(big.mark = ".", decimal.mark = ","))+
  #scale_colour_manual(name = "", labels = c("#141313" = "Média por SE"), values = c("#141313" = "#141313")) +
  geom_text(aes(x=minData_n, y=obitosNovos, label = format(obitosNovos, big.mark = ".", decimal.mark = ",")), colour = "black", hjust = 0.5,
  vjust = -1, fontface = "bold", size=14) +
  #geom_label(aes(x=minData_n, y=smaObitosNovos, label = format(smaObitosNovos, big.mark = ".", decimal.mark = ",")), colour = "black", hjust = 0.5, vjust = 0.4, fontface = "bold", size=14) +
  labs(title = "Óbitos da covid-19 por SE da notificação",
    x = "Semana epidemiológica", y = "Número de óbitos novos de covid") +
  theme_ipsum(grid = F, base_size = 16, axis_text_size = 30) +
  theme(legend.position = "bottom",
        axis.line.x = element_line(colour = "black"),
        axis.ticks.x = element_line(colour = "black"),
        axis.title.x = element_text(size = 30),
        axis.text.x = element_text(size = 30),
        axis.title.y = element_text(size = 30),
        plot.title = element_text(size = 30),
        legend.text = element_text(size = 30))
```

```{r}
# ============================================================================
# SALVAR GRÁFICOS DE BARRAS
# Exporta como PNG em alta resolução (retina)
# Dimensões: 550x400mm para apresentação em tela grande/impressão
# NOTA: Atualizar a pasta da SE a cada semana
# ============================================================================
#setwd("C:/Users/pbrte/OneDrive - Ministério da Saúde/Área de Trabalho/cards/")
#setwd("C:/Users/wanderley.junior/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/graficos/SE 13 2024/")##ATUALIZAR

setwd("C:/Users/audencio.victor/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/graficos/SE 19 2024/")##ATUALIZAR



#setwd("C:/Users/pbrte/OneDrive - Ministério da Saúde/14. Análises COE-COVID/ROTINAS/cards semanal/graficos/SE 47 2023/")##ATUALIZAR
#setwd("C:/Users/pbrte/OneDrive - Ministério da Saúde/")

ggsave(Plot_casos_mes, width = 550, height = 400, units = "mm", file ="casos_SE.png", dpi = "retina")
ggsave(Plot_obitos_mes, width = 550, height = 400, units = "mm", file ="obitos_SE.png", dpi = "retina")


```

```{r}
# ============================================================================
# INFORMAÇÕES PARA PREENCHIMENTO DO CARD SEMANAL
# Os resultados abaixo são usados para preencher manualmente os cards
# de divulgação semanal do Ministério da Saúde
# ============================================================================

# TOTAL ACUMULADO DE CASOS NO BRASIL
DT_CONTROL %>% filter(ABRANGENCIA ==1, data==max(data)) %>% select(casosAcumulado)
```

```{r}
# TOTAL ACUMULADO DE ÓBITOS NO BRASIL
DT_CONTROL %>% filter(ABRANGENCIA ==1, data==max(data)) %>% select(obitosAcumulado)
```

```{r}
# TOTAL DE CASOS POR ANO CALENDÁRIO
DT_CONTROL %>% filter(ABRANGENCIA ==1) %>% mutate(Ano=format(data,"%Y")) %>% group_by(Ano) %>% summarise("Casos por ano"=sum(casosNovos))
```

```{r}
# TOTAL DE ÓBITOS POR ANO CALENDÁRIO
DT_CONTROL %>% filter(ABRANGENCIA ==1) %>% mutate(Ano=format(data,"%Y")) %>% group_by(Ano) %>% summarise("Óbitos por ano"=sum(obitosNovos))
```
